### ISSUE TITLE
Problem extracting files on Linux

### ISSUE THREAD

**Issue by NicholasConstanci** [SydMontague/DSCSTools#3]
When you use the extract command on Linux (I'm using KDE Neon, which is Ubuntu-based), the files are extracted using Windows slashes, so it creates files like "images_de\filename.img" inside the DSDBS and DSDBSP folders.
Tried doing a lot of things by hand to install the undub mod, like renaming and moving files to the correct folders and making all files follow this "folder\filename.extension" naming with no actual folders, nothing worked.

**Comment by SydMontague** [comment]
The tool isn't really optimized for *nix systems right now and might not work properly due to the format relying on Windows file separators, hence the \ in the file names.

However, I was still able to extract and repack a seemingly valid .mvgl archive (-> the game managed to access files from it) on my Linux machine, so in theory you should be able to apply the undub patch with it by using the name format created by the extractor.

Alternatively, as a workaround using the Windows binary with Wine might be an option.

**Comment by NicholasConstanci** [comment]
> The tool isn't really optimized for *nix systems right now and might not work properly due to the format relying on Windows file separators, hence the \ in the file names.
> 
> However, I was still able to extract and repack a seemingly valid .mvgl archive (-> the game managed to access files from it) on my Linux machine, so in theory you should be able to apply the undub patch with it by using the name format created by the extractor.
> 
> Alternatively, as a workaround using the Windows binary with Wine might be an option.

Thanks for the answer, 
I installed it by sending the files to someone using Windows and they did it for me there after my multiple failed attempts at making it work (tried renaming both ways and leaving as it was, but none worked for some reason, it repacked but without the changed files).
Just created the issue to let you know about it, it's not an urgent issue anyway since not many people use Linux.

**Comment by SydMontague** [comment]
The next release will improve Linux support, taking care of the path differences by itself.

-> extract will create the proper folder structure
-> pack will convert paths to Windows in the process
